services:
  methone-panel:
    image: methone-panel
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    container_name: methone-panel
    hostname: methone-panel
    networks:
      - default
    volumes:
      - ./src:/var/www/
    restart: always
    ports:
      - 8080:80
    depends_on:
      methone-panel-mariadb:
        condition: service_healthy
    tty: true

  methone-panel-vite:
    image: "node:22-alpine"
    user: root
    container_name: methone-panel-vite
    hostname: methone-panel-vite
    working_dir: /home/node/app
    environment:
      - CI=true
    volumes:
      - ./src/:/home/node/app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    networks:
      - default
    ports:
      - 5173:5173
    depends_on:
      - methone-panel
    tty: true

  methone-panel-mariadb:
    image: mariadb
    container_name: methone-panel-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      - default
    volumes:
      - ./db/mysql/:/var/lib/mysql/
    restart: always
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mariadb", "--user=root", "--password=${MARIADB_ROOT_PASSWORD}", "--execute", "SELECT 1;" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  methone-panel-phpmyadmin:
    image: methone-panel-phpmyadmin
    build:
      context: ./
      dockerfile: docker/phpmyadmin/Dockerfile
    container_name: methone-panel-phpmyadmin
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    hostname: methone-panel-phpmyadmin
    networks:
      - default
    restart: always
    ports:
      - 8081:80

networks:
  default:
    name: methone-panel_default
